
server:
  port: 8080



spring:
  application:
    name: clinic-system

  datasource:
    url: 'jdbc:postgresql//localhost:5432/clinic_system?ssl=false&sslmode=allow'
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: create
    generate-ddl: true